### ISSUE TITLE
Sandbank For Storing Data

### ISSUE THREAD

**Issue by B0zy** [dxura/darkrp#9]
The Following is a Issue from the Original DarkRP Github Repo. 
https://github.com/sousou63/DarkRP/issues/186
```
Hi! Hope you are well!

I have to apologise in advance because this is basically just going to be me shamelessly plugging my own library...

So I noticed that it looks like the plan currently is to store game data in a traditional database: https://github.com/sousou63/DarkRP/blob/main/code/Persistence/Database.cs

I was wondering if you had considered using my database library? (https://github.com/anthonysharpy/sandbank)

I think the advantages of this would be:

    It's faster
    It's a lot simpler for people to implement (currently for the traditional database approach to work you'd need to host an API and a database, which is probably a headache for most people)
    It's cheaper (no need to pay for database/API hosting)
    You can start implementing it now (rather than waiting for a feature that Facepunch might never add)
    It would simplify your code

If you think it sounds like a good idea then I can even make a PR implementing this for you.

If you have any questions please ask 😄
```

Using this would be much more beneficial in the long run then simply relying on a homemade solution or simply using .json files.

**Comment by dimmerly** [comment]
@anthonysharpy I have noticed your sqlite-like storage layer previously before your issue. 

We would be interested in your contribution to implementing your solution for dxura/darkrp which is based of HC1/Nicked. 

While the previous version had a pseudo json system, this version has no persistence yet.

There's a few requirements 
- For now, we want each user to store their own data, but in future we want a dedicated server holding this information - there must be a clear way to switch in future.
- The persistence has to be implemented in a way that it depends on an interface rather than directly on your  package.
Darkrp code -> Interface -> Your persistence package 

Additionally it would be nice if it was somewhat encrypted, at least so it's more effort than it's worth to manipulate. This is not required.

The basic data we want persisted at the moment would be the player balance, then maybe roles/playtime later on.

Let me know if you're interested in working on this, should be straight forward I believe.

**Comment by anthonysharpy** [comment]
@dimmerly Thanks for the reply!

> For now, we want each user to store their own data, but in future we want a dedicated server holding this information - there must be a clear way to switch in future.

I think this is doable

**Comment by anthonysharpy** [comment]
@dimmerly Thanks for the reply!

> For now, we want each user to store their own data, but in future we want a dedicated server holding this information - there must be a clear way to switch in future.

Sounds doable. My library supports saving on the client and server. Saving on the client is disabled by default but this can be enabled with a boolean in the config file.

> Additionally it would be nice if it was somewhat encrypted, at least so it's more effort than it's worth to manipulate. This is not required.

Yeah, there's no way to make it 100% uneditable if it's being stored on the client. But I can obfuscate it as you suggest such that 99% people won't bother trying. I probably wouldn't do this for the initial implementation, but would probably add it as a new feature to the library soon after, and then you can enable it when it suits you.

> The persistence has to be implemented in a way that it depends on an interface rather than directly on your package.
Darkrp code -> Interface -> Your persistence package

I see where you are coming from with this. However some things to bear in mind:

- The library uses a custom [Saved] attribute, which cannot be interfaced, so it is technically impossible to fully interface the implementation.
- Usually what I do is implement a `Save()` method on the entity (e.g. the player), and this handles all the saving. This is not an interface, but it functions like one since if you ever wanted to use a different method of saving, you can just replace the code here. So by doing this it's sort of the same thing.
- I think it would be difficult if not impossible to provide an interface that would fit any possible future storage solution, as there's just too many possibilities.
- The library requires calling very few lines of code, so replacing it is not really a hassle (in fact, the interface would probably have more code than the actual implementation).

But let me go and make an example implementation and then you can decide if it's too tightly coupled or not.

> The basic data we want persisted at the moment would be the player balance, then maybe roles/playtime later on.

Easy peasy.

**Comment by anthonysharpy** [comment]
Just implemented the obfuscation thing :-)

![image](https://github.com/user-attachments/assets/935b720b-1a16-4cbe-a1bf-b393bd20b6c1)

Will try and get a PR ready

**Comment by anthonysharpy** [comment]
PR https://github.com/dxura/darkrp/pull/12

**Comment by anthonysharpy** [comment]
Seems this is merged so feel free to close

If you have any questions feel free to let me know, or you can raise an issue on my repo 😄
